server:
  port: 8080

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:agentdb
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect    
  servlet:
    multipart:
      max-file-size: 10MB
    
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method